apiVersion: v1
kind: Secret
metadata:
  name: {{ include "airflowpulse.fullname" . }}
  labels:
    {{- include "airflowpulse.labels" . | nindent 4 }}
type: Opaque
stringData:
  airflow-api-password: {{ .Values.airflow.apiPassword | quote }}
  {{- if .Values.airflow.metadataDSN }}
  metadata-dsn: {{ .Values.airflow.metadataDSN | quote }}
  {{- end }}
  {{- if .Values.alerting.telegramBotToken }}
  telegram-bot-token: {{ .Values.alerting.telegramBotToken | quote }}
  {{- end }}
  {{- if .Values.grafana.token }}
  grafana-token: {{ .Values.grafana.token | quote }}
  {{- end }}
